// <auto-generated />
namespace AulaEF_CF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ContextPersonsAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContextPersonsAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202210101541443_ContextPersonsAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
